[build]
  functions = "netlify/functions"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

[[redirects]]
  from = "/api/submit-photo"
  to = "/.netlify/functions/submit-photo"
  status = 200

[[redirects]]
  from = "/api/submit-video"
  to = "/.netlify/functions/submit-video"
  status = 200

[[redirects]]
  from = "/api/submit-message"
  to = "/.netlify/functions/submit-message"
  status = 200

[[redirects]]
  from = "/api/get-submissions"
  to = "/.netlify/functions/get-submissions"
  status = 200
